# Generated by Django 3.0.2 on 2020-01-30 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('fname', models.CharField(max_length=20)),
                ('mname', models.CharField(max_length=20, null=True)),
                ('lname', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, verbose_name='UserEmail')),
                ('active', models.BooleanField(default=True)),
                ('admin', models.BooleanField(default=False)),
                ('editor', models.BooleanField(default=False)),
                ('surfer', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
