# Generated by Django 3.0.2 on 2020-01-31 11:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200131_1703'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditorProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_no', models.IntegerField()),
                ('profile_pic', models.ImageField(null=True, upload_to='editor/')),
                ('address', models.CharField(max_length=50)),
                ('user_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
