# Generated by Django 3.0.2 on 2020-02-07 10:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('editor', '0003_auto_20200203_1616'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editor.NewsPost')),
                ('surfer_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NewsComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=500)),
                ('news_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editor.NewsPost')),
                ('surfer_detail', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CommentComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surfer.NewsComment')),
                ('surfer_detail', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
