# Generated by Django 2.2.1 on 2020-02-11 11:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0004_newspost_like_no'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('surfer', '0003_followeditor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_list', models.ManyToManyField(to='editor.NewsPost')),
                ('surfer_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
