# Generated by Django 3.0.2 on 2020-01-30 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('summary', models.CharField(max_length=1000)),
                ('body', models.TextField()),
                ('image', models.ImageField(upload_to='news/')),
                ('img_source', models.CharField(max_length=50)),
                ('epub_date', models.DateTimeField(auto_now_add=True)),
                ('ppub_date', models.DateTimeField()),
                ('category', models.CharField(max_length=20)),
                ('pub_status', models.BooleanField(default=False)),
                ('editor_detail', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.User')),
            ],
        ),
    ]
