# Generated by Django 3.0.2 on 2020-01-31 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspost',
            name='image',
            field=models.ImageField(null=True, upload_to='news/'),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='img_source',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
