# Generated by Django 3.0.2 on 2020-02-03 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0002_auto_20200131_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspost',
            name='ppub_date',
            field=models.DateTimeField(null=True),
        ),
    ]
