# Generated by Django 3.0.2 on 2020-02-07 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0003_auto_20200203_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspost',
            name='like_no',
            field=models.IntegerField(default=0),
        ),
    ]
