# Generated by Django 2.2.1 on 2020-02-12 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0004_newspost_like_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspost',
            name='view_no',
            field=models.IntegerField(default=0),
        ),
    ]
